---
title: "RNA-seq analysis"
author: "Mark"
date: "9 July 2018"
output: html_document
---


```{r}
install.packages("RColorBrewer")
source("http://www.bioconductor.org/biocLite.R")
biocLite(c("DESeq2","edgeR"))
```

```{r}
library(DESeq2)
library(edgeR)
```

Reading the sample information

```{r}
sampleinfo <- read.delim("data/SampleInfo.txt")
View(sampleinfo)
```

Reading the counts

```{r}
seqdata <- read.delim("data/GSE60450_Lactation-GenewiseCounts.txt")
View(seqdata)
```

```{r}
dim(seqdata)
countdata <- seqdata[,3:14]
View(countdata)
rownames(countdata) <- seqdata[,1]
```

```{r}
?substr
substr("January",1,3)
substr(month.name,1,3)
```

```{r}
colnames(countdata) <- substr(colnames(countdata),1,7)
colnames(countdata) == sampleinfo$SampleName
```

```{r}
?cpm
myCPM <- cpm(countdata)
head(myCPM)
```


```{r}
colSums(countdata)
sum(countdata[,1])/1e6
countdata[1,1]/(sum(countdata[,1])/1e6)
myCPM <- cpm(countdata)
head(myCPM)
```

```{r}
plot(myCPM[,1],countdata[,1],xlim=c(0,3),ylim=c(0,50))
abline(h=10)
```

```{r}
plot(myCPM[,2],countdata[,2],xlim=c(0,3),ylim=c(0,50))
abline(h=10,col="blue")
abline(v=0.5,col="blue")
```

```{r}
is_expressed <- myCPM > 0.5
head(is_expressed)

sum(is_expressed[1,])
samples_expressed <- rowSums(is_expressed)
table(samples_expressed)
```
```{r}
barplot(table(samples_expressed))
sampleinfo
keep <- samples_expressed >=2
summary(keep)

counts_keep <- countdata[keep,]
dim(countdata)
dim(counts_keep)
```

```{r}
library(DESeq2)

dds <- DESeqDataSetFromMatrix(counts_keep,
                              colData = sampleinfo,
                              design = ~ CellType)
dds
```


```{r}
colData(dds)
boxplot(assay(dds))
```

```{r}
vsd <- vst(dds)
vsd
boxplot(assay(vsd),las=2)

```

```{r}
sampleDists <- dist(t(assay(vsd)))
sampleDists
sampleDistMatrix <- as.matrix(sampleDists)

if(!require(pheatmap)) install.packages("pheatmap")

library(pheatmap)

sampleDistMatrix
rownames(sampleinfo) <- sampleinfo$SampleName

pheatmap(sampleDistMatrix,
         annotation_col=sampleinfo[,3:4])

```

```{r}
plotPCA(vsd, intgroup="CellType")
```
```{r}
plotPCA(vsd, intgroup=c("Status","CellType"))
```

```{r}
sampleinfo <- read.delim("data/SampleInfo_Corrected.txt")

dds <- DESeqDataSetFromMatrix(counts_keep,
                              colData = sampleinfo,
                              design = ~ CellType)

vsd <- vst(dds)
plotPCA(vsd,intgroup="CellType")
```


```{r}
design(dds)
colData(dds)
```

```{r}
de <- DESeq(dds)
results(de)
results.cellType <- as.data.frame(results(de))
results.cellType
dim(results.cellType)
```


```{r}

x <- results.cellType$padj < 0.05
table(x)
results.cellType[(is.na(x)),]
sum(na.omit(x))

results.ordered <- results.cellType[order(results.cellType$padj),]
write.csv(results.ordered,file="cellType_de_results.csv")


```

```{r}
dds.status <- dds
design(dds.status) <- ~Status
de.status <- DESeq(dds.status)

results.status <- results(de.status)
results.status
```

```{r}
results(de, contrast=c("CellType","luminal","basal"))
results(de, contrast=c("CellType","basal","luminal"))
```

```{r}
results(de.status)
colData(dds.status)
results(de.status, contrast=c("Status","pregnant","virgin"))

```

```{r}
venn_data <- data.frame(CellType = results.cellType$padj < 0.05,Status = results.status$padj < 0.05)
head(venn_data)
library(limma)
vennDiagram(venn_data)
```

```{r}
DESeq2::plotMA(de.status)
```

```{r}
results.ordered <- results.status[order(results.status$padj),]
results.ordered
plotCounts(dds,"67111",intgroup="Status")
```

```{r}
library(org.Mm.eg.db)
source("http://www.bioconductor.org/biocLite.R")
biocLite("org.Mm.eg.db")
```


```{r}
columns(org.Mm.eg.db)
```

```{r}
keytypes(org.Mm.eg.db)
```

```{r}
select(org.Mm.eg.db, keys="67111",
       keytype = "ENTREZID",
       columns = c("SYMBOL","GENENAME","GO","PATH"))
```

```{r}
ann <- select(org.Mm.eg.db, keys=rownames(results.ordered),
              keytype="ENTREZID",columns=c("SYMBOL","GENENAME"))
head(ann)
```
```{r}
dim(ann)
dim(results.ordered)
```

```{r}
table(ann$ENTREZID == rownames(results.ordered))
results.annotated <- cbind(results.ordered,ann)
results.annotated

write.csv(results.annotated, file="de_status_annotated.csv")
```

```{r}
N <- 50
top_genes <- results.annotated$ENTREZID[1:N]
assay(vsd)[top_genes,]
rownames(sampleinfo) <- sampleinfo$SampleName

pdf("my_pretty_heatmap.pdf")
pheatmap(assay(vsd)[top_genes,],
         annotation_col = sampleinfo[,3:4],
         labels_row = results.annotated$SYMBOL[1:N])
dev.off()

png("my_pretty_heatmap.png")
pheatmap(assay(vsd)[top_genes,],
         annotation_col = sampleinfo[,3:4],
         labels_row = results.annotated$SYMBOL[1:N])
dev.off()
```

```{r}
background_genes <- results.annotated$SYMBOL
write.table(background_genes, "background_genes.txt",sep="\t",row.names = FALSE,quote=FALSE)

de_genes <- results.annotated$SYMBOL[results.annotated$padj < 0.5 & results.annotated$log2FoldChange > 1,]

write.table(de_genes,file="de_genes.txt",sep="\t",row.names = FALSE,quote=FALSE)
```

```{r}
biocLite("fgsea")
library(fgsea)
```

```{r}
results.stat.ordered <- results.ordered[order(results.ordered$stat,decreasing = TRUE),]

results.stat.ordered
ranks <- results.stat.ordered$stat
names(ranks) <- rownames(results.stat.ordered)

load("data/mouse_H_v5.rdata")
pathways <- Mm.H

fgseaRes <- fgsea(pathways, ranks,nperm=1000)
fgseaRes

fgseaRes[order(padj),]
plotEnrichment(pathways[["HALLMARK_CHOLESTEROL_HOMEOSTASIS"]],ranks)
plotEnrichment(pathways[["HALLMARK_WNT_BETA_CATENIN_SIGNALING"]],ranks)

```

