---
title: "R Introduction"
author: "Mark"
date: "9 July 2018"
output: html_document
---

Some arithmetic
```{r}
2 + 2
2 - 2
2 * 2 
10 / 2
```

Something more complicated

```{r}
2 + (2 * 3 )
(2 +2) * 3
2 + 2 * 3
```


```{r}
pi
sin(pi)
log(1)
```

Let's talk about variables

```{r}
x <- 10
x
myNumber <- 25
x + myNumber
#y + myNumber
log(x)
```


```{r}
y <- x + myNumber
y
rm(y)

my_number <- 50
```

```{r}
seq(from=3, to=20,by=4)
?seq
seq(3, 20 ,4)
```

```{r}
rnorm(n=10)
rnorm(n=10, mean=5)
```

```{r}
?round
round(pi,digits = 3)
seq(from = 2, to=20,length.out=5)
myRandomNumbers <- rnorm(n=1000,mean=2,sd = 3)
min(myRandomNumbers)
max(myRandomNumbers)
mean(myRandomNumbers)
```


```{r}
x <- c(3,4,5,6)
x
x <- 3:6
x
x[1]
x[4]
y <- 2:4
y

x
x[y]

y <- c(1,3)
x[y]

myRandomNumbers[y]
```

```{r}
otherRandomNumbers <- myRandomNumbers * 2
```

```{r}
x <- c("A","B","C","D")
x

#x <- c(A,B,C,D)
```

```{r}
x <- c(TRUE,FALSE,TRUE)
x
myRandomNumbers <-myRandomNumbers[1:10]
myRandomNumbers > 4
myRandomNumbers[c(1,3,7,8)]

myRandomNumbers[myRandomNumbers < 4]

x <- c("A","B","C","C","D")
x == "C"

x != "C"

```

