---
title: "gapminder analysis"
author: "Mark"
date: "9 July 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
```

```{r}
list.files()
```

```{r}
file.exists("gapminder.csv")
```

```{r}

gapminder <- read.csv("gapminder.csv")
```

```{r}
myfile <- file.choose()
myfile
gapminder <- read.csv(myfile)
```

```{r}
View(gapminder)
```

```{r}
test <- read.delim("gapminder.csv")
test
dim(gapminder)
dim(test)
```

```{r}
countries <- gapminder$country
summary(gapminder)
```
```{r}
lifeExp <- gapminder$lifeExp
pop <- gapminder$pop

max(lifeExp)
min(pop)

lifeExp <- round(lifeExp)
pop <- gapminder$pop / 1000000
pop[1:5]
```

Subsetting Data Frames

```{r}
gapminder[1,2]
gapminder[2,1]
gapminder[c(1,2,3),c(1,2)]
```

```{r}
gapminder[c(1,2,3),]
gapminder[1:3,]
```

```{r}
gapminder[gapminder$lifeExp < 40,]
```

```{r}
gapminder[gapminder$country == "Zambia",]
```


```{r}
grep("land",gapminder$country) 
gapminder[grep("land",gapminder$country),]

```

```{r}
gapminder[gapminder$country == "Zambia" & gapminder$lifeExp < 40,]
```


```{r}
gapminder[gapminder$pop < 1000000 & gapminder$year == 2002,]
```

```{r}
lowLifeExp <- gapminder[gapminder$lifeExp < 45 & gapminder$year == 2007,]
lowLifeExp
summary(lowLifeExp)
table(lowLifeExp$continent)
```

```{r}
gapminder[gapminder$country == "Zambia" | gapminder$country == "Zimbabwe",]
```

```{r}
gapminder[gapminder$lifeExp == max(gapminder$lifeExp),]
gapminder[gapminder$pop == min(gapminder$pop),]

gapminder[which.max(gapminder$lifeExp),]
gapminder[804,]
```

```{r}
sort(myRandomNumbers,decreasing = TRUE)
```

```{r}
gapminder[order(gapminder$pop),]
```

```{r}
gapminder_by_year <- gapminder[order(gapminder$year,gapminder$pop),]
write.csv(gapminder_by_year,file="gapminder_by_year.csv")
```


```{r}
hist(gapminder$lifeExp)
```

```{r}
plot(gapminder$pop, gapminder$lifeExp)
```

```{r}
barplot(table(gapminder$continent))
```

```{r}
boxplot(gapminder$gdpPercap ~ gapminder$continent)
```

```{r}
plot(gapminder$pop, gapminder$lifeExp,
     col="red",
     pch=16,
     ylab="Life Expectancy",
     xlab="Population",
     main="Plot title")
```

```{r}
boxplot(gapminder$gdpPercap ~ gapminder$continent,
        col=c("red","orange","green","blue","purple"))
?plot

```

```{r}
euroData <- gapminder[gapminder$continent == "Europe" & gapminder$year == 2002,]

afrData <- gapminder[gapminder$continent == "Africa" & gapminder$year == 2002,]

plot(euroData$pop, euroData$lifeExp,col="red"
     ,pch=16)
```

```{r}
plot(euroData$pop, euroData$lifeExp,col="red"
     ,pch=16)
points(afrData$pop,afrData$lifeExp,col="blue")

```
```{r}
plot(euroData$pop,euroData$lifeExp,
     xlim=c(0,8e7),
     ylim=c(30,90))
points(afrData$pop,afrData$lifeExp,col="red")
```

```{r}
plot(gapminder$pop, gapminder$lifeExp)
```

```{r}
bigPops <- gapminder[gapminder$pop > 4e8,]
bigPops

```

```{r}
plot(gapminder$pop, gapminder$lifeExp,pch=16)
points(bigPops$pop,bigPops$lifeExp,col="red",pch=16)
abline(v=4e8,lty=2)
```

